# Generated by Django 3.0.3 on 2020-02-10 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='writings',
            new_name='writing',
        ),
    ]
